[pelican]
author = "Elliot Simpson"
sitename = "Turbopelican"

timezone  = "Pacific/Auckland"

path = "turbopelican/docs"

theme = "themes/plain-theme"

article_paths = []
page_paths = [""]
path_metadata = "(?P<path_no_ext>.*)\\..*"
page_save_as = "{path_no_ext}.html"
direct_templates = []

static_paths = ["static", "images"]

author_feed_atom = "None"
author_feed_rss = "None"
category_feed_atom = "None"
feed_all_atom = "None"
translation_feed_atom = "None"

[pelican.markdown]
output_format = "html5"

[pelican.markdown.extension_configs]
'markdown.extensions.codehilite' = {css_class = "codehilite"}
'markdown.extensions.extra' = {}
'markdown.extensions.meta' = {}

[[pelican.extra_path_metadata]]
origin = "static/favicon.ico"
path = "favicon.ico"

[[pelican.extra_path_metadata]]
origin = "images/logo.svg"
path = "logo.svg"

[publish]
site_url = "https://turbopelican.github.io"
delete_output_directory = true
